### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by colinmj** [Ilya-Meer/Insta-News#3]
More of a personal thing and not a serious problem, but maybe add some more comments in code! I find it super helpful

**Comment by samyok** [comment]
I'll add comments to some of it :)

**Comment by samyok** [comment]
Is there any reason why 22 lines were minified in the scripts.min.js file? I don't think you would gain much of a speed advantage with it minified...

**Comment by Ilya-Meer** [comment]
Good question, this project was my introduction to Gulp so I tried to incorporate a css minifying task into my workflow. You're right, it's not worth it for this project, but perhaps in the future it will come in handy for larger projects.
